### ISSUE TITLE
Nested <Collapse/>s, parent <Collapse/> is also changed

### ISSUE THREAD

**Issue by phun-ky** [nkbt/react-collapse#69] opened 2016-08-08 10:56 UTC
Probably not quite related to https://github.com/nkbt/react-collapse/issues/58, but related to https://github.com/nkbt/react-collapse/issues/40.

```
import React, { Component, PropTypes } from 'react';
import { IndexLink, Link } from 'react-router';
import Collapse from 'react-collapse';

export default class Menu extends Component {

  static propTypes = {
    isMenuToggled: PropTypes.bool.isRequired
  };

  constructor(props){
    super(props);

    this.state = {
      isSubMenuToggled: false
    };
  }

  render() {

    const { isSubMenuToggled } = this.state;
    const { isMenuToggled } = this.props;

    return (
      <nav ref="menu" className="menu" role="navigation">
        <Collapse key="menuCollapse" keepCollapsedContent={true} isOpened={isMenuToggled}>
          <ul className="menu-list mypages-nav-active">
            <li className="menu-item menu-mainItem is--parent">
              <Collapse key="subMenuCollapse" className="menu-main" isOpened={isSubMenuToggled} keepCollapsedContent={true}>
                <ul className="menu-sublist">
                  <li className="menu-item">
                    <span className="menu-row">
                      <IndexLink activeClassName="is--active" className="menu-link" to="/">
                        Overview
                      </IndexLink>
                    </span>
                  </li>
                </ul>
              </Collapse>
            </li>
          </ul>
        </Collapse>
      </nav>
    );
  }
}
```

When using nested `<Collapse/>`s, if I open the inner `<Collapse/>`, the outer `<Collapse/>`'s height is also adjusted.

**Comment by nkbt** [comment] 2016-08-08 11:16
This is intended behavior.

If you wish to fix hight of parent - you can add `onHeightReady` callback and use `fixedHeight` prop

**Comment by nkbt** [comment] 2016-08-08 11:18
Flickering issue of #40 should be most likely fixed by removing `defaultStyles` of react-motion. Though it would lead to quite a refactor...

**Comment by phun-ky** [comment] 2016-08-08 11:24
The problem is that the "flicker" is happening due to the parent `<Collapse/>`'s height is changed ~1s after the child `<Collapse/>`.

**Comment by nkbt** [comment] 2016-08-08 11:27
I reckon you have a lot of components rendered, height measuring is usually very fast and happens pretty much instantaneously. Alternatively, parent collapse does not know about children height change and changes only when you pass new props to it (which may happen by some other data changes).

**Closed** 2017-04-18 01:45 UTC
Labels: answered, question
