### ISSUE TITLE
instantly collapses if rerendered during collapse

### ISSUE THREAD

**Issue by kentor** [nkbt/react-collapse#59] opened 2016-07-01 00:12 UTC
I'm trying to implement an accordion component with react-collapse. The issue is that if I call setState to collapse an element, then call setState again shortly after but before the first collapse finishes, the first collapse animation finishes right away.

Here's a repro: https://jsbin.com/viwalageta/edit?js,output

Clicking on Header 2 shows what I mean.

Not sure if this is an issue with react-collapse or react-motion.

**Comment by nkbt** [comment] 2016-07-01 01:14
The problem is that when you set state after 50ms you force component to re-render. Collapse then checks "okay, we now do fresh render, we are closed - okay, here is `height: 0` then" and therefore it instantly collapses.

This happens because of using `defaultStyle` here: https://github.com/nkbt/react-collapse/blob/master/src/Collapse.js#L177 There was a reason to use defaultStyle quite a while ago, but it can be probably fixed in some way.

Usually to avoid these issues I keep Collapse isolated from anything except `isOpened` changes (or its  styles) and use `shouldComponentUpdate` so it does not have any unnecessary re-renders.

Your fix would be to avoid extra unnecessary re-render (that you invoke be `setState`). Maybe isolating Collapse with extra container or something.

**Comment by nkbt** [comment] 2016-08-08 12:03
https://jsbin.com/xewacukubo/edit?html,js,output not fixed yet with 2.3.2 =(

**Comment by nkbt** [comment] 2016-08-13 09:42
Just published `react-collapse@next` (not `latest` channel yet until better tested) with full rewrite, which fixes this issue. Give it a shot if you are keen.

**Closed by nkbt** 2016-08-13 09:42 UTC
Labels: in progress
