### ISSUE TITLE
provide a flag for linear-no-motion mode

### ISSUE THREAD

**Issue by boyangwang** [nkbt/react-collapse#91] opened 2016-09-20 04:55 UTC
Is it possible to have the option to not use react-motion, instead a simple linear unveiling?

Is a PR is desired, can you point to some rough direction?

**Comment by nkbt** [comment] 2016-09-20 05:20
At the moment react-collapse is based on react-motion, which implements spring animation. It does not support linear animation.
I was thinking of replacing react-motion with simple tweening function soon, so it will become totally possible (less buggy and more performant at the same time). This is why v3 is still in alpha.

Can't give any rough estimation on that, bit busy organizing some local js/node workshops recently, but will have perf/ui optimization soon on my day job project and this looks like a good candidate for perf.

**Comment by phun-ky** [comment] 2016-10-31 10:17
Tbh, the consumers of this dependency should be able to set their own animation timing function, animation length and animation delay. The best approach would be setting this with CSS, but that might be a to big of change.

**Comment by nkbt** [comment] 2017-02-13 11:48
Closing as duplicate of https://github.com/nkbt/react-collapse/issues/145

**Closed by nkbt** 2017-02-13 11:48 UTC
Labels: duplicate, enhancement

**Comment by phun-ky** [comment] 2017-02-13 11:57
@nkbt why close the original issue? shouldn't it be the other way around?

**Comment by nkbt** [comment] 2017-02-13 11:58
The second one will lead to a more generic solution, thus using that one as the main.
